---
title: "visualizations"
output: html_document
---

```{r}
library(tidyverse)
library(meta)
```

```{r}
load('results/NWU_results.rda')
load('results/UPENN_results.rda')
```

```{r}
heatmap(NWU_results$elix_mat)
heatmap(UPENN_results$elix_mat)
```


```{r}
propagated_codes <- UPENN_results$propagated_codes

right_join0 <- function(x, y, fill = 0L, ...) {
  z <- right_join(x, y, ...)
  tmp <- setdiff(names(z), names(y))
  tidyr::replace_na(z, setNames(as.list(rep(fill, length(
    tmp
  ))), tmp))
}

temp_code_plot <- propagated_codes %>%
  select(- prop_new_codes, - n_new_codes) %>% 
  pivot_longer(-c(early_code))
temp_code_plot %>%  ggplot(aes(
  y = fct_reorder(early_code, value, .fun = max),
  x = value,
  fill = name
)) +
  facet_wrap( ~ name, scales = 'free_x') +
  geom_col() +
  rcartocolor::scale_fill_carto_d() +
  guides(fill = FALSE) +
  labs(y = NULL, x = NULL, fill = NULL) +
  theme_bw()

    
```


## Comorbidities by Diagnosis

```{r}
UPENN_results$first_hosp_results$icd_tables$other_obfus_table
```


```{r}
# scores_neuro %>% 
#   distinct(patient_num, concept_code, `Neurological Disease Category`) %>%
#   left_join(index_scores_elix %>% select(patient_num, elixhauser_score), by = "patient_num") %>%
#   filter(!is.na(elixhauser_score)) %>% 
#   ggplot(aes(y = concept_code, x = elixhauser_score, fill = concept_code)) + 
#   facet_grid(rows = vars(`Neurological Disease Category`),
#              scales = 'free', space = 'free') +
#   geom_boxplot(alpha = 0.6) + 
#   scale_fill_viridis_d(guide = FALSE, direction = -1) +
#   labs(x = 'Elixhauser score', y = NULL) +
#   NULL +
#   theme(panel.grid = element_blank(),
#         legend.title = element_text(),
#         strip.text.y = element_text(angle = 0),
#         panel.spacing.x = unit(10, "points"),
#         panel.spacing.y = unit(0, "points"))
```

