---
title: "Demo Figure"
author: "Meg Hutch"
date: "3/22/2021"
output: html_document
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(dplyr)
library(gridGraphics)
library(gridExtra)
library(ggpubr)
library(DT)
library(kableExtra)
library(cowplot)
library(RColorBrewer)
library(glue)
theme_set(theme_bw() +
  theme(panel.grid.minor = element_blank()))
```

```{r}
rdas <- list.files(
  path = "results",
  pattern = ".rda",
  full.names = TRUE
)
for (rda in rdas) {
  load(rda)
}

rm(rdas, rda)
site_google_url <- "https://docs.google.com/spreadsheets/d/1epcYNd_0jCUMktOHf8mz5v651zy1JALD6PgzobrGWDY/edit?usp=sharing"

site_params <- googlesheets4::read_sheet(site_google_url, sheet = 1)
site_avails <- googlesheets4::read_sheet(site_google_url, sheet = 2)
sorted_sites <- site_avails %>%
  filter(`data received` == "Y", is.na(excluded)) %>%
  pull(siteid)

# sorted_sites <- rev(c(
#   "APHP", "FRBDX", "HPG23", "ICSM", "MGB", "NWU", "UPENN", "UPITT"
# ))

sites_wo_race <- site_params %>%
  filter(!include_race) %>%
  pull(siteid)

# colorBlindGrey6 <-
#   c("#0072B2", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#CC79A7")

results <- paste(sorted_sites, "results", sep = "_")
```

## Demographic Data

### Pre-processing

```{r}
demo_table_list <- list()

for (i in results) {
  tmp <- get(i)
  demo_table_list[[i]] <- tmp[[c(
    "first_hosp_results",
    "cpns_results",
    "demo_table"
  )]] %>%
    select(site, everything())
}
combined_table_wide <- bind_rows(demo_table_list) %>%
  # site level differences in variable names require tolower()
  # rename race.other to avoid recoding conflicts with age_group.other
  mutate(
    site = toupper(site),
    variable = tolower(variable),
    variable = if_else(variable == "race.other", "race.Other", variable),
    variable = if_else(variable == "age_group.other", "age_group.Unknown", variable),
    Demo_var = sub("\\..*", "", variable),
    Demo_var_i = sub(".*\\.", "", variable) %>%
      gsub("_", " ", .) %>%
      str_to_title() %>%
      recode(
        `00to02` = "0-2",
        `03to05` = "3-5",
        `06to11` = "6-11",
        `12to17` = "12-17",
        `18to25` = "18-25",
        `26to49` = "26-49",
        `50to69` = "50-69",
        `70to79` = "70-79",
        `80plus` = "80+",
        race.white = "White",
        race.american_indian = "American Indian",
        `Hawaiian Pacific Islander` = "Hawaiian/Pacific Islander",
        `Hispanic Latino` = "Hispanic/Latino",
        `False` = "Not Readmitted",
        `True` = "Readmitted"
      )
  )
```

```{r}
other_table_list <- list()
for (i in results) {
  tmp <- get(i)
  other_table_list[[i]] <- tmp[[c(
    "first_hosp_results",
    "cpns_results",
    "other_obfus_table"
  )]] %>%
    select(site, everything())
}

combined_other_table_wide <- bind_rows(other_table_list) %>%
  filter(grepl("Mean|Median", name))
```


```{r fig.height=10}
medians_df <- combined_other_table_wide %>%
  filter(grepl("Median", name)) %>%
  pivot_longer(None:Both, names_to = "neuro_type") %>%
  replace_na(list(value = "0 [0, 0]")) %>%
  mutate(
    median_val = as.numeric(gsub(" \\[[^()]*\\]", "", value)),
    min_max = gsub("\\[([^()]*)\\]|.", "\\1", value, perl = T),
    # min_val = as.numeric(gsub("^(.*?),.*", "\\1", min_max)),
    min_val = as.numeric(gsub(",.*$", "", min_max)),
    max_val = as.numeric(gsub(".*,\\s*", "", min_max)),
    grouped_var = gsub("Mean |Median | \\[Min, Max\\]| \\(SD\\)", "", name)
  ) %>%
  mutate_if(is.numeric, function(x) ifelse(is.infinite(x), 0, x))
# medians_df[!is.finite(medians_df)] <- 0
medians_df %>%
  ggplot(aes(x = neuro_type, color = site)) +
  # geom_point() +
  geom_pointrange(
    size = 0.2,
    aes(
      y = median_val,
      ymin = min_val,
      ymax = max_val
    ),
    position = position_dodge2(width = 0.8)
  ) +
  facet_grid(rows = vars(grouped_var), scales = "free") +
  # scale_color_brewer(palette = "Dark2") +
  rcartocolor::scale_color_carto_d() +
  labs(y = "Median [Min, Max]", x = "Neurological conditions")
```


```{r fig.height=10}
alpha_threshold <- qnorm(0.975)
means_df <- combined_other_table_wide %>%
  filter(grepl("Mean", name)) %>%
  pivot_longer(None:Both, names_to = "neuro_type") %>%
  replace_na(list(value = "0 (0)")) %>%
  mutate(
    mean_val = as.numeric(gsub(" \\([^()]*\\)", "", value)),
    se_val = as.numeric(gsub("\\(([^()]*)\\)|.", "\\1", value, perl = T)),
    grouped_var = gsub("Mean |Median | \\[Min, Max\\]| \\(SD\\)", "", name)
  )
means_df %>%
  ggplot(aes(x = neuro_type, color = site)) +
  geom_pointrange(
    size = 0.2,
    aes(
      x = neuro_type, y = mean_val,
      ymin = mean_val - alpha_threshold * se_val,
      ymax = mean_val + alpha_threshold * se_val,
    ),
    position = position_dodge2(width = 0.8)
  ) +
  facet_grid(rows = vars(grouped_var), scales = "free") +
  rcartocolor::scale_color_carto_d() +
  labs(y = "Mean [95% CI]", x = "Neurological conditions")
```

```{r}
vars_to_process <- unique(combined_other_table_wide$name)

processed_list <- list()

for (i in vars_to_process) {
  mod_table <- combined_other_table_wide %>%
    rename("var" = name) %>%
    filter(var == i) %>%
    mutate(
      site = toupper(site),
      None = sub("(\\(.*|\\[.*)", "", None),
      Peripheral = sub("(\\(.*|\\[.*)", "", Peripheral),
      Central = sub("(\\(.*|\\[.*)", "", Central),
      Both = sub("(\\(.*|\\[.*)", "", Both)
    ) %>%
    mutate(across(None:Both, as.numeric)) %>%
    as_tibble() %>%
    select(-site, -var) %>%
    summarise_all(list(
      mean = mean,
      median = median,
      min = min,
      max = max
    ),
    na.rm = TRUE
    )

  processed_list[[i]] <- mod_table
}

# Mean of the median distribution is the best estimate for the median:
# It's the BLUE[est] (best least unbiased estimator).
other_table_compiled <- bind_rows(processed_list, .id = "Table 1") %>%
  # select(-contains("mean")) %>%
  filter(grepl("Median", `Table 1`)) %>%
  mutate(across(ends_with("mean"), ~ round(., 1))) %>%
  # get average of the medians
  mutate(
    None = glue("{None_mean} [{None_min}, {None_max}]"),
    Peripheral = glue("{Peripheral_mean} [{Peripheral_min}, {Peripheral_max}]"),
    Central = glue("{Central_mean} [{Central_min}, {Central_max}]"),
    Both = glue("{Both_mean} [{Both_min}, {Both_max}]"),
    N = NA
  ) %>%
  select(`Table 1`, N, None, Peripheral, Central, Both)
```

```{r}
processed_list_figs <- list()
for (i in vars_to_process) {
  mod_table <- combined_other_table_wide %>%
    rename("var" = name) %>%
    filter(var == i) %>%
    mutate(
      site = toupper(site),
      None = sub("(\\(.*|\\[.*)", "", None),
      Peripheral = sub("(\\(.*|\\[.*)", "", Peripheral),
      Central = sub("(\\(.*|\\[.*)", "", Central),
      Both = sub("(\\(.*|\\[.*)", "", Both)
    ) %>%
    mutate(across(None:Both, as.numeric))

  processed_list_figs[[i]] <- mod_table
}

other_table_for_figs <- bind_rows(processed_list_figs)
```

**Site Level Results**

```{r echo=FALSE,message=FALSE, warning=FALSE, fig.height=10}
other_table_for_figs %>%
  mutate(
    me = stringr::word(var),
    grouped_var = gsub("Mean |Median | \\[Min, Max\\]| \\(SD\\)", "", var)
  ) %>%
  pivot_longer(
    cols = None:Both,
    names_to = "type"
  ) %>%
  mutate(type = factor(type, levels = c("None", "Central", "Peripheral", "Both"))) %>%
  ggplot(aes(y = value, x = type, fill = site)) +
  facet_grid(vars(grouped_var), vars(me), scales = "free") +
  geom_bar(stat = "identity", position = "dodge", colour = "black") +
  scale_fill_brewer(palette = "Dark2") +
  labs(x = NULL, y = NULL, fill = NULL)
```

## Table One

```{r}
ordered_vars <- c(
  "all", "sex", "age_group", "race",
  "readmitted", "severity", "survival"
)
tableOne_inter <- combined_table_wide %>%
  group_by(variable, Demo_var, Demo_var_i) %>%
  summarise(across(
    starts_with("n_var"),
    function(x) sum(x, na.rm = TRUE)
  ), .groups = "drop")

row_order <- c(
  "All Patients", "Female", "Male",
  "0-2", "3-5", "6-11", "12-17", "18-25",
  "26-49", "50-69", "70-79", "80+", "Unknown",
  "American Indian", "Asian", "Black",
  "Hawaiian/Pacific Islander",
  "Hispanic/Latino", "Other", "White",
  "Median Elixhauser score [Min, Max]",
  "Median length of stay [Min, Max]",
  "Non-Severe", "Severe",
  "Median time to severe [Min, Max]",
  "Alive", "Deceased", "Median time to death [Min, Max]",
  "Not Readmitted", "Readmitted",
  "Median time to first readmission [Min, Max]",
  "Median number of readmissions [Min, Max]"
)

get_table_n <- function(var) {
  tableOne_raw %>%
    filter(`Table 1` == var) %>%
    pull(N)
}

tableOne_raw <- tableOne_inter %>%
  filter(Demo_var == "sex") %>%
  summarise(across(where(is.numeric), sum)) %>%
  data.frame(
    variable = "all",
    Demo_var = "all",
    Demo_var_i = "All Patients",
    .
  ) %>%
  bind_rows(tableOne_inter) %>%
  mutate(
    N = rowSums(across(where(is.numeric))),
    Demo_var = factor(Demo_var, levels = ordered_vars)
  ) %>%
  group_by(Demo_var) %>%
  mutate(across(
    starts_with("n_var"),
    function(x) {
      paste0(x, " (", round(x / sum(x, na.rm = TRUE) * 100, 1), "%", ")")
    }
  )) %>%
  ungroup() %>%
  arrange(Demo_var) %>%
  select(Demo_var_i, N, starts_with("n_var")) %>%
  `colnames<-`(gsub(
    x = names(.),
    pattern = "n_var_",
    replacement = ""
  )) %>%
  rename("Table 1" = Demo_var_i) %>%
  bind_rows(other_table_compiled) %>%
  slice(match(row_order, `Table 1`))

tableOne_compiled <- tableOne_raw %>%
  mutate(
    N = case_when(
      grepl("Median length of stay", `Table 1`) ~ get_table_n("All Patients"),
      grepl("Median time to severe", `Table 1`) ~ get_table_n("Severe"),
      grepl("death", `Table 1`) ~ get_table_n("Deceased"),
      grepl("readmission", `Table 1`) ~ get_table_n("Readmitted"),
      grepl("Median Elixhauser score", `Table 1`) ~ get_table_n("All Patients"),
      TRUE ~ N
    )
  )

kbl(tableOne_compiled) %>%
  add_header_above(c(
    " ",
    "",
    "No Neurological Disease" = 1,
    "Neurological Disease" = 3
  )) %>%
  kable_paper("striped", full_width = F) %>%
  pack_rows("Gender", 2, 3) %>%
  pack_rows("Age", 4, 13) %>%
  pack_rows("Race & Ethnicity", 14, 20) %>%
  pack_rows("Comorbidites", 21, 21) %>%
  pack_rows("Hospital Course", 22, 22) %>%
  pack_rows("Severity", 23, 25) %>%
  pack_rows("Survival", 26, 28) %>%
  pack_rows("Readmission", 29, 32)
```

```{r fig.height=15, fig.width=11}
combined_table <- combined_table_wide %>%
  pivot_longer(
    cols = starts_with("n_var"),
    names_to = "Dx",
    values_to = "Count"
  ) %>%
  replace_na(list(Count = 0)) %>%
  mutate(Dx = gsub("n_var_", "", Dx) %>%
    fct_relevel(c("None", "Central", "Peripheral", "Both")))
```

### Diagnoses

```{r}
neuro_icds_10 <-
  readxl::read_excel("public-data/2020-02-22_neuro-icd10_CNSvPNS.xlsx") %>%
  rename(
    "icd" = `ICD-10`,
    "pns_cns" = `Nervous system Involvement (1=central, 2=peripheral)`
  ) %>%
  mutate(pns_cns = as.factor(pns_cns) %>% fct_recode(
    Central = "1",
    Peripheral = "2"
  )) %>%
  select(icd, `Neurological Disease Category`, pns_cns, `ICD-10 Description`) %>%
  rename("description" = `ICD-10 Description`) %>%
  mutate(concept_type = "icd-10")

neuro_icds_9 <- read.csv("public-data/icd9_tab_CNSvPNS.csv") %>%
  rename(
    "Neurological Disease Category" = "Neurological.Disease.Category",
    "pns_cns" = `Nervous.system.Involvement..1.central..2.peripheral.`,
    "icd_description" = `icd9_desc`
  ) %>%
  mutate(
    pns_cns = as.factor(pns_cns) %>% fct_recode(
      Central = "1",
      Peripheral = "2"
    ),
    concept_type = "DIAG-ICD9"
  ) %>%
  select(icd, `Neurological Disease Category`, pns_cns, icd_description) %>%
  rename("description" = icd_description) %>%
  mutate(concept_type = "icd-9")

icds <- rbind(neuro_icds_10, neuro_icds_9)

diag_table_list <- list()

for (i in results) {
  tmp <- get(i)
  tmp_diag <- tmp[[c(
    "first_hosp_results",
    "icd_tables",
    "demo_table"
  )]]
  tmp_diag$site <- tmp[["site"]]
  diag_table_list[[i]] <- tmp_diag %>%
    filter(variable == "sex.female" | variable == "sex.male") %>%
    select(site, contains("n_var"))
}

diag_table_wide <- bind_rows(diag_table_list)


diag_counts <- colSums(Filter(is.numeric, diag_table_wide), na.rm = TRUE) %>% 
  data.frame()

diag_counts <- tibble::rownames_to_column(diag_counts, "icd") %>%
  mutate(icd = gsub("n_var_", "", icd)) %>%
  rename("sum_neuro_icd" = ".") %>%
  left_join(., icds, by = "icd") %>%
  group_by(`Neurological Disease Category`) %>%
  mutate(sum_neuro_cat = sum(sum_neuro_icd)) %>%
  arrange(desc(sum_neuro_cat)) %>% 
  ungroup() %>% 
  select(icd, `Neurological Disease Category`, 
         pns_cns, description, concept_type, sum_neuro_icd,
         sum_neuro_cat)

datatable(diag_counts)
```

### Comordities

```{r}
comorb_table_list <- list()

for (i in results) {
  tmp <- get(i)
  tmp_comorb <- tmp[[c(
    "first_hosp_results",
    "binary_results",
    "elix_obfus_table1"
  )]]
  tmp_comorb$site <- tmp[["site"]]
  comorb_table_list[[i]] <- tmp_comorb %>%
    select(site, Comorbidity, n_Total)
}
comorb_table_wide <- bind_rows(comorb_table_list) %>%
  pivot_wider(
    id_cols = "site",
    names_from = "Comorbidity",
    values_from = "n_Total"
  )

comorb_counts <- colSums(Filter(is.numeric, comorb_table_wide), na.rm = TRUE) %>%
  data.frame()

comorb_counts <- tibble::rownames_to_column(comorb_counts, "Comorbidity") %>%
  rename("total" = ".") %>%
  arrange(desc(total))

datatable(comorb_counts)
```


## Figures

```{r echo=T, message=FALSE, warning=FALSE, results='hide'}
race_dx <- combined_table %>%
  filter(Demo_var == "race") %>%
  mutate(Demo_var_i = as.factor(Demo_var_i))

age_dx <- combined_table %>%
  filter(Demo_var == "age_group") %>%
  mutate(Demo_var_i = as.factor(Demo_var_i))
```

```{r gender-plot}
showtext::showtext_auto()
female <- intToUtf8(9792)
male <- intToUtf8(9794)
gender_count <- combined_table %>%
  filter(Demo_var == "sex") %>%
  group_by(site, Demo_var_i) %>%
  summarise(total_count = sum(Count, na.rm = TRUE), .groups = "drop")

gender_plot <- gender_count %>%
  mutate(total_count = if_else(Demo_var_i == "Male", -total_count, total_count)) %>%
  ggplot(aes(
    y = fct_relevel(site, sorted_sites),
    x = total_count, color = Demo_var_i
  )) +
  geom_col(position = "identity", fill = "grey70") +
  scale_color_manual(values = c("white", "white")) +
  scale_x_continuous(
    breaks = c(-10000, -5000, -2000, 0, 2000, 5000),
    labels = c(10000, 5000, 2000, 0, 2000, 5000),
    trans = ggallin::ssqrt_trans
  ) +
  geom_vline(xintercept = 0, color = "white") +
  geom_text(
    data = . %>% filter(Demo_var_i == "Male"),
    aes(
      y = site, x = total_count - 6 * sqrt(abs(total_count)),
      label = abs(total_count)
    ), color = "grey10", size = 3
  ) +
  geom_text(
    data = . %>% filter(Demo_var_i == "Female"),
    aes(
      y = site, x = total_count + 7 * sqrt(abs(total_count)),
      label = abs(total_count)
    ), color = "grey10", size = 3
  ) +
  geom_text(
    data = . %>% filter(site == "VA5", Demo_var_i == "Female"),
    aes(y = length(sorted_sites), x = total_count - 50), fontface = 2,
    label = female, size = 3, color = "white"
  ) +
  geom_text(
    data = . %>% filter(site == "VA5", Demo_var_i == "Male"),
    aes(y = length(sorted_sites), x = total_count + 200), fontface = 2,
    label = male, size = 3, color = "white"
  ) +
  labs(
    y = NULL,
    x = "Number of male/female patients per site",
    fill = NULL
  ) +
  theme(
    legend.position = "None",
    # plot.margin = margin(15, 5.5, 15.5, 55.5),
    axis.ticks.y = element_blank(),
    panel.grid.major.y = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    panel.spacing.y = unit(0, "pt"),
    strip.background = element_blank(),
    strip.placement = "inside",
    legend.background = element_blank(),
    legend.key.height = unit(1, "line"),
    legend.title = element_text(hjust = 0, size = 9)
  ) +
  NULL
```

```{r age-plot}
age_sum <- age_dx %>%
  filter(Demo_var == "age_group") %>%
  mutate(Demo_var_i = fct_relevel(
    Demo_var_i,
    c(
      "0-2",
      "3-5",
      "6-11",
      "12-17",
      "18-25",
      "26-49",
      "50-69",
      "70-79",
      "80+"
    )
  )) %>%
  select(site, Demo_var_i, Dx, Count) %>%
  distinct() %>%
  group_by(site, Demo_var_i) %>%
  summarise(
    total_count = sum(Count, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  group_by(site) %>%
  mutate(freq = total_count / sum(total_count, na.rm = TRUE))

cc <- scales::seq_gradient_pal("white", "#25796C")(seq(0, 1, length.out = 11))[-1]

age_plot <- age_sum %>%
  mutate(Demo_var_i = Demo_var_i %>% fct_relevel("Other", after = 0)) %>%
  ggplot(aes(
    # y = fct_reorder(site, freq * (1 + 20 * (Demo_var_i == "80+"))),
    y = fct_reorder2(site, Demo_var_i, -freq),
    x = freq, fill = fct_rev(Demo_var_i)
  )) +
  geom_col() +
  # scale_fill_viridis_d(direction = -1, option = 'D') +
  scale_fill_manual(values = cc) +
  scale_x_continuous(labels = scales::percent_format()) +
  labs(x = "Age group proportion", y = NULL, fill = NULL) +
  guides(fill = guide_legend(nrow = 1, reverse = TRUE)) +
  coord_cartesian(expand = FALSE) +
  theme(legend.position = "top") +
  theme(
    panel.grid = element_blank(),
    legend.key.height = unit(3, "mm")
  ) +
  NULL
```

```{r race-plot}
race_sum <- race_dx %>%
  mutate(Demo_var_i = fct_relevel(
    Demo_var_i,
    c(
      "Other",
      "Hawaiian/Pacific Islander",
      "American Indian",
      "Hispanic/Latino",
      "Asian",
      "Black",
      "White"
    )
  )) %>%
  filter(Demo_var == "race", !site %in% sites_wo_race) %>%
  select(site, Demo_var_i, Dx, Count) %>%
  distinct() %>%
  group_by(site, Demo_var_i) %>%
  summarise(
    total_count = sum(Count, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  group_by(site) %>%
  mutate(freq = total_count / sum(total_count, na.rm = TRUE))

race_plot <- race_sum %>%
  ggplot(aes(
    y = fct_reorder2(site, Demo_var_i, freq),
    x = freq,
    fill = fct_rev(Demo_var_i)
  )) +
  geom_col() +
  rcartocolor::scale_fill_carto_d(palette = 6) +
  scale_x_continuous(labels = scales::percent_format()) +
  labs(x = "Race/ethnic group proportion", y = NULL, fill = NULL) +
  guides(fill = guide_legend(nrow = 1, reverse = TRUE)) +
  coord_cartesian(expand = FALSE) +
  theme(legend.position = "top") +
  theme(
    panel.grid = element_blank(),
    legend.key.height = unit(3, "mm")
  ) +
  NULL
```

```{r}
my_breaks <- function(x) {
  if (max(x) < 0.2) {
    NULL
  } else if (max(x) < 0.8) {
    seq(0, 1, 0.2)
  } else {
    seq(0.2, 1, 0.2)
  }
}

race_plot2 <- race_sum %>%
  ggplot(aes(
    # y = fct_reorder2(site, Demo_var_i, freq),
    y = site,
    x = freq,
    fill = fct_rev(Demo_var_i)
  )) +
  geom_col() +
  rcartocolor::scale_fill_carto_d(palette = 6) +
  scale_x_continuous(
    breaks = my_breaks,
    labels = scales::percent_format(accuracy = 1)
  ) +
  labs(x = "Race/ethnic group proportion", y = NULL, fill = NULL) +
  guides(fill = guide_legend(nrow = 1, reverse = TRUE)) +
  coord_cartesian(expand = FALSE) +
  theme(legend.position = "top") +
  facet_grid(cols = vars(Demo_var_i), scales = "free", space = "free") +
  theme(
    strip.background = element_blank(),
    strip.text.x = element_blank(),
    panel.grid = element_blank(),
    legend.key.height = unit(3, "mm"),
    panel.spacing = unit(0, "lines")
  ) +
  NULL
```


```{r}
age_plot2 <- age_sum %>%
  mutate(Demo_var_i = Demo_var_i %>% fct_relevel("Other", after = 0)) %>%
  ggplot(aes(
    y = site,
    x = freq, fill = fct_rev(Demo_var_i)
  )) +
  geom_col() +
  # scale_fill_viridis_d(direction = -1, option = 'D') +
  scale_fill_manual(values = cc) +
  scale_x_continuous(
    breaks = my_breaks,
    labels = scales::percent_format(accuracy = 1)
  ) +
  labs(x = "Age group proportion", y = NULL, fill = NULL) +
  guides(fill = guide_legend(nrow = 1, reverse = TRUE)) +
  coord_cartesian(expand = FALSE) +
  facet_grid(cols = vars(Demo_var_i), scales = "free", space = "free") +
  theme(legend.position = "top") +
  theme(
    # strip.background = element_blank(),
    # strip.text.x = element_blank(),
    panel.grid = element_blank(),
    legend.key.height = unit(3, "mm"),
    panel.spacing = unit(0, "lines")
  ) +
  NULL
age_plot2
```


```{r combine-plots, eval=FALSE, fig.height=7, fig.width=9, include=FALSE}
demo_plot <- cowplot::plot_grid(gender_plot, age_plot, race_plot,
  ncol = 1,
  rel_heights = c(1, 1.1, 0.95)
)

demo_plot

# ggsave('figs/demo.png', demo_plot, height = 8, width = 8)
```

### LPCA deviance explained

How much deviance is explained with 10 principal components for 30 comorbidity types?

Across sites, 10 principal components explained above 75% of the deviance.

```{r}
pca_dev <- list()
for (i in results) {
  tmp <- get(i)
  if (!is.null(tmp$deviance_expl)) {
    pca_dev[[i]] <- data.frame(site = tmp$site, dev_expl = tmp$deviance_expl)
  }
}

# site_avails %>%
#   filter(`data received` == 'Y') %>%
#   pull(siteid) %>%
#   setdiff(bind_rows(pca_dev) %>% pull(site))

bind_rows(pca_dev) %>%
  ggplot(aes(x = fct_reorder(site, -dev_expl), y = dev_expl, group = 1)) +
  geom_point() +
  geom_line() +
  coord_cartesian(ylim = c(0, 1)) +
  labs(y = "Comorbidity LPCA deviance explained", x = NULL)
```

## Other exploratory analyses

```{r echo=T, message=FALSE, warning=FALSE, results='hide'}
neuro_types <- c("None", "Central", "Peripheral", "Both")

surv_plot <- combined_table %>%
  filter(Demo_var == "survival") %>%
  mutate(Dx = gsub("n_var_", "", Dx) %>% fct_relevel(neuro_types)) %>%
  ggplot(aes(
    x = Dx,
    y = Count,
    fill = Demo_var_i
  )) +
  # geom_violin(alpha = 0.2) +
  geom_point(color = "white", shape = 21, size = 3) +
  scale_fill_manual(values = c("#FFE3CB", "#E58605")) +
  facet_wrap(~Demo_var_i, scale = "free_y", nrow = 1) +
  xlab("") +
  ylab("") +
  theme_bw() +
  theme(legend.position = "none") +
  NULL

# scales::seq_gradient_pal("white", '#CC61AF')(seq(0,1,length.out = 10))[-1]
severity_plot <-
  combined_table %>%
  filter(Demo_var == "severity") %>%
  mutate(Dx = gsub("n_var_", "", Dx) %>% fct_relevel(neuro_types)) %>%
  ggplot(aes(
    x = Demo_var_i,
    y = Count,
    fill = Demo_var_i
  )) +
  # geom_violin(alpha = 0.2) +
  geom_point(color = "white", shape = 21, size = 3) +
  scale_fill_manual(values = c("#F6DCED", "#CC61AF")) +
  facet_wrap(~Dx, scale = "free_y", nrow = 1) +
  xlab("") +
  ylab("") +
  theme_bw() +
  theme(legend.position = "none") +
  NULL

readmit_plot <- ggplot(
  combined_table %>%
    filter(Demo_var == "readmitted") %>%
    filter(!Dx == "None"),
  aes(
    x = site, y = Count, group = site,
    fill = site
  )
) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_fill_viridis_d() +
  # rcartocolor::scale_fill_carto_d() +
  facet_grid(Dx ~ Demo_var_i, scale = "free_y") +
  # facet_wrap(~Dx, nrow = 1) +
  xlab("") +
  ylab("") +
  theme_bw() +
  theme(
    legend.position = "none",
    axis.text.x = element_text(size = 8, angle = 45, hjust = 1)
  )

# Create legend
legend_b <- get_legend(
  race_plot +
    guides(color = guide_legend(nrow = 1)) +
    theme(
      legend.position = "top",
      legend.title = element_blank()
    )
)
```

```{r}
combined_table %>%
  filter(Demo_var_i == "Alive") %>%
  select(site, starts_with("prop")) %>%
  distinct() %>%
  pivot_longer(-site) %>%
  mutate(name = gsub("prop_", "", name) %>% fct_relevel(neuro_types)) %>%
  ggplot(aes(x = name, y = value, group = site, color = site)) +
  geom_point() +
  rcartocolor::scale_color_carto_d() +
  geom_line() +
  scale_y_continuous(limits = c(0, 1)) +
  labs(x = NULL, y = "Proportion survived", color = NULL) +
  theme(legend.position = "top") +
  NULL

combined_table %>%
  filter(Demo_var_i == "Alive") %>%
  select(site, starts_with("prop")) %>%
  distinct() %>%
  pivot_longer(-site) %>%
  mutate(name = gsub("prop_", "", name) %>% fct_relevel(neuro_types)) %>%
  ggplot(aes(x = name, y = value)) +
  geom_boxplot() +
  geom_point() +
  scale_y_continuous(limits = c(0, 1)) +
  labs(x = NULL, y = "Proportion survived") +
  NULL

combined_table %>%
  filter(Demo_var_i == "Severe") %>%
  select(site, starts_with("prop")) %>%
  distinct() %>%
  pivot_longer(-site) %>%
  mutate(name = gsub("prop_", "", name) %>% fct_relevel(neuro_types)) %>%
  ggplot(aes(x = name, y = value)) +
  geom_boxplot() +
  geom_point() +
  scale_y_continuous(limits = c(0, 1)) +
  labs(x = NULL, y = "Proportion severe") +
  NULL
```

point size = count?

```{r message=FALSE, warning=FALSE, fig.width=10}
# Arrange plots
# p1 <- plot_grid(sex_plot, age_plot, labels=c("A", "B"), ncol = 2, nrow = 1)
# p2 <- plot_grid(race_plot, labels = c("C"), ncol = 1)
plot_grid(severity_plot, surv_plot, labels = c("E", "F"), ncol = 2, nrow = 1)
```
